id: A51911B58
title: A Sādhana of White Sarasvatī
type: translation
pechas:
- I3755437B
- I04F3C763
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:35.421276
  last_modified_at: 2023-01-04 13:11:35.421283
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3755437B/AEDB: FC76
  I04F3C763/BF96: FC76
